about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Raw format to OME-TIFF converter
  dev_url: https://github.com/glencoesoftware/raw2ometiff/


package:
  name: "raw2ometiff"
  version: "0.2.3"

build:
  noarch: generic
  number: 1

source:
  url: https://github.com/glencoesoftware/raw2ometiff/releases/download/v0.2.3/raw2ometiff-0.2.3.zip
  sha256: 017b151556649943ea870b8bec60fcb86588e9584972323a6c54097398209387

requirements:
  host:
  run:
    - openjdk =11

testextra:
  recipe-maintainers:
    - ome
