package:
  name: "raw2ometiff"
  version: "0.2.4"

build:
  number: 2

source:
  url: https://github.com/glencoesoftware/raw2ometiff/releases/download/v0.2.4/raw2ometiff-0.2.4.zip
  sha256: 5c6b351b45930953c41b79595b13ebec976b685434498fd7b48828a332ac4953

requirements:
  host:
  run:
    - openjdk

test:
  commands:
    - raw2ometiff --help

testextra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Raw format to OME-TIFF converter
  dev_url: https://github.com/glencoesoftware/raw2ometiff/
