package:
  name: "raw2ometiff"
  version: "0.2.6"

build:
  number: 0

source:
  url: https://github.com/glencoesoftware/raw2ometiff/releases/download/v0.2.6/raw2ometiff-0.2.6.zip
  sha256: fb32604f484a68835134d1ffe6d1a9eff2f30fac19f92960dd8c42ba7d61c9a1

requirements:
  host:
  run:
    - openjdk

test:
  commands:
    - raw2ometiff --help

testextra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Raw format to OME-TIFF converter
  dev_url: https://github.com/glencoesoftware/raw2ometiff/
