package:
  name: "raw2ometiff"
  version: "0.2.7"

build:
  number: 0

source:
  url: https://github.com/glencoesoftware/raw2ometiff/releases/download/v0.2.7/raw2ometiff-0.2.7.zip
  sha256: 9c9f7ba990e71d4556cd14921b263a3456aa461f89933a47b039514bbf945da4

requirements:
  host:
  run:
    - openjdk

test:
  commands:
    - raw2ometiff --help

testextra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Raw format to OME-TIFF converter
  dev_url: https://github.com/glencoesoftware/raw2ometiff/
